# Generated by Django 5.1.7 on 2026-05-16 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('camping_capacity', models.PositiveIntegerField(default=0)),
                ('has_cabins', models.BooleanField(default=False)),
                ('working_hours', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parque',
                'verbose_name_plural': 'Parques',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='sistema_app.park')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
                'unique_together': {('park', 'name')},
            },
        ),
        migrations.AddField(
            model_name='park',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='parks', to='sistema_app.service'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('CAMPING', 'Camping'), ('CABIN', 'Cabaña')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('people', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('PAST', 'Pasada')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='sistema_app.cabin')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='sistema_app.park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['park', 'visit_type', 'status'], name='sistema_app_park_id_0b09f4_idx'), models.Index(fields=['start_date', 'end_date'], name='sistema_app_start_d_4e5c3c_idx')],
            },
        ),
    ]
