# Generated by Django 5.1.7 on 2026-05-19 06:16

import django.utils.timezone
from django.db import migrations, models


def cleanup_unverified_users(apps, schema_editor):
    """Borra los Users inactivos que estaban a medio verificar.
    """
    EmailVerification = apps.get_model("sistema_app", "EmailVerification")
    User = apps.get_model("auth", "User")
    user_ids = list(EmailVerification.objects.values_list("user_id", flat=True))
    # CASCADE en EmailVerification.user borra también los registros de EV.
    User.objects.filter(id__in=user_ids, is_active=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_app', '0005_emailverification'),
    ]

    operations = [
        migrations.RunPython(cleanup_unverified_users, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Registro pendiente',
                'verbose_name_plural': 'Registros pendientes',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
