# Generated by Django 5.1.7 on 2026-05-23 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_app', '0006_pendingregistration_delete_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('attempted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Intento de inicio de sesión',
                'verbose_name_plural': 'Intentos de inicio de sesión',
                'ordering': ('-attempted_at',),
                'indexes': [models.Index(fields=['username', 'attempted_at'], name='sistema_app_usernam_d1a393_idx')],
            },
        ),
    ]
