# Generated by Django 5.1.7 on 2026-05-24 21:13

import uuid
from django.db import migrations, models


def generate_tokens(apps, schema_editor):
    """Asigna un UUID único a cada reserva existente."""
    Reservation = apps.get_model('sistema_app', 'Reservation')
    for reservation in Reservation.objects.all():
        reservation.checkin_token = uuid.uuid4()
        reservation.save(update_fields=['checkin_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_app', '0007_loginattempt'),
    ]

    operations = [
        # 1) Agregar campo sin unique para no chocar con filas existentes.
        migrations.AddField(
            model_name='reservation',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # 2) Llenar cada fila con un UUID único.
        migrations.RunPython(generate_tokens, reverse_code=migrations.RunPython.noop),
        # 3) Aplicar unique + index ahora que todas las filas tienen valor único.
        migrations.AlterField(
            model_name='reservation',
            name='checkin_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('PAST', 'Pasada'), ('USED', 'Usada')], default='ACTIVE', max_length=10),
        ),
    ]
