# Generated by Django 5.1.7 on 2026-06-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_app', '0010_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.PositiveIntegerField()),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_logs', to='sistema_app.park')),
            ],
            options={
                'ordering': ['-cancelled_at'],
            },
        ),
    ]
