"""
Pruebas del flujo de check-in (QR + transición ACTIVE → USED).

Cubre:
    - Modelo: campo checkin_token autogenerado, mark_as_used() y sus errores
    - Servicio: ReservationCheckinService.check_in() y casos de fallo
    - Admin: endpoints custom (scan, data, confirm) con y sin sesión staff
"""

import pytest

pytestmark = pytest.mark.unit

import uuid

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.urls import reverse

from sistema_app.models import Reservation
from sistema_app.services import ReservationCheckinService


# ===========================================================================
# Modelo: checkin_token y mark_as_used
# ===========================================================================

@pytest.mark.django_db
class TestReservationCheckinToken:
    def test_token_autogenerated(self, active_reservation):
        """Accede al campo checkin_token de una reservación recién creada; verifica que existe y es uuid.UUID."""
        assert active_reservation.checkin_token is not None
        assert isinstance(active_reservation.checkin_token, uuid.UUID)

    def test_tokens_are_unique(self, db, user, park, cabin, camping_spot, season_start, season_end_date):
        """Crea dos reservaciones distintas y compara sus checkin_token; verifica que son diferentes entre sí."""
        r1 = Reservation.objects.create(
            user=user, park=park, lodging=cabin,
            start_date=season_start, end_date=season_end_date, people=1,
        )
        r2 = Reservation.objects.create(
            user=user, park=park, lodging=camping_spot,
            start_date=season_start, end_date=season_end_date, people=1,
        )
        assert r1.checkin_token != r2.checkin_token


@pytest.mark.django_db
class TestReservationMarkAsUsed:
    def test_mark_as_used_changes_status(self, active_reservation):
        """Llama mark_as_used() sobre una reservación activa y recarga desde BD; verifica que el status cambia a USED."""
        active_reservation.mark_as_used()
        active_reservation.refresh_from_db()
        assert active_reservation.status == Reservation.Status.USED

    def test_mark_as_used_on_cancelled_raises(self, cancelled_reservation):
        """Llama mark_as_used() sobre una reservación cancelada; verifica que lanza ValidationError."""
        with pytest.raises(ValidationError):
            cancelled_reservation.mark_as_used()

    def test_mark_as_used_on_past_raises(self, past_reservation):
        """Llama mark_as_used() sobre una reservación con status PAST; verifica que lanza ValidationError."""
        with pytest.raises(ValidationError):
            past_reservation.mark_as_used()

    def test_mark_as_used_on_used_raises(self, active_reservation):
        """Llama mark_as_used() dos veces sobre la misma reservación; verifica que la segunda llamada lanza ValidationError."""
        active_reservation.mark_as_used()
        active_reservation.refresh_from_db()
        with pytest.raises(ValidationError):
            active_reservation.mark_as_used()


# ===========================================================================
# Servicio
# ===========================================================================

@pytest.mark.django_db
class TestReservationCheckinService:
    def test_active_transitions_to_used(self, active_reservation):
        """Llama check_in() sobre una reservación activa; verifica que el status cambia a USED en el objeto y en BD."""
        result = ReservationCheckinService.check_in(active_reservation)
        assert result.status == Reservation.Status.USED
        active_reservation.refresh_from_db()
        assert active_reservation.status == Reservation.Status.USED

    def test_double_checkin_raises(self, active_reservation):
        """Realiza check_in() dos veces consecutivas sobre la misma reservación; verifica que la segunda lanza ValidationError."""
        ReservationCheckinService.check_in(active_reservation)
        with pytest.raises(ValidationError):
            ReservationCheckinService.check_in(active_reservation)

    def test_cancelled_raises(self, cancelled_reservation):
        """Llama check_in() sobre una reservación cancelada; verifica que lanza ValidationError."""
        with pytest.raises(ValidationError):
            ReservationCheckinService.check_in(cancelled_reservation)

    def test_past_raises(self, past_reservation):
        """Llama check_in() sobre una reservación con status PAST; verifica que lanza ValidationError."""
        with pytest.raises(ValidationError):
            ReservationCheckinService.check_in(past_reservation)


# ===========================================================================
# is_cancellable rechaza reservas USED
# ===========================================================================

@pytest.mark.django_db
class TestIsCancellableWithUsed:
    def test_used_reservation_not_cancellable(self, active_reservation):
        """Hace check-in a una reservación activa y luego llama is_cancellable(); verifica que retorna False."""
        ReservationCheckinService.check_in(active_reservation)
        active_reservation.refresh_from_db()
        assert active_reservation.is_cancellable() is False


# ===========================================================================
# Endpoints del admin (integration tests)
# ===========================================================================

@pytest.fixture
def superuser_client(client, db):
    """Cliente Django logueado como superusuario para acceder al admin."""
    user = User.objects.create_superuser(
        username="admin", email="admin@test.com", password="AdminPass123!",
    )
    client.force_login(user)
    return client


@pytest.mark.django_db
@pytest.mark.integration
class TestAdminScanView:
    def test_scan_page_requires_staff(self, client):
        """Cliente sin autenticar hace GET al endpoint de escaneo QR; verifica que redirige al login del admin."""
        url = reverse("admin:sistema_app_reservation_scan")
        response = client.get(url)
        assert response.status_code in (302, 301)
        assert "login" in response["Location"]

    def test_scan_page_returns_200_with_superuser(self, superuser_client):
        """Superusuario hace GET al endpoint de escaneo QR; verifica que responde HTTP 200 con el texto 'Escanear QR'."""
        url = reverse("admin:sistema_app_reservation_scan")
        response = superuser_client.get(url)
        assert response.status_code == 200
        assert b"Escanear QR" in response.content


@pytest.mark.django_db
@pytest.mark.integration
class TestAdminCheckinDataEndpoint:
    def test_returns_json_with_reservation_data(self, superuser_client, active_reservation):
        """Superusuario hace GET al endpoint con el token de una reservación activa; verifica el JSON con id, status y can_check_in."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_data",
            args=[active_reservation.checkin_token],
        )
        response = superuser_client.get(url)
        assert response.status_code == 200
        data = response.json()
        assert data["id"] == active_reservation.pk
        assert data["status"] == Reservation.Status.ACTIVE
        assert data["can_check_in"] is True

    def test_unknown_token_returns_404(self, superuser_client):
        """Superusuario hace GET con un UUID que no existe en BD; verifica que responde HTTP 404."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_data",
            args=[uuid.uuid4()],
        )
        response = superuser_client.get(url)
        assert response.status_code == 404

    def test_used_reservation_reports_cannot_checkin(self, superuser_client, active_reservation):
        """Se hace check-in a la reservación y luego se consulta el endpoint; verifica que el JSON indica can_check_in False y status USED."""
        ReservationCheckinService.check_in(active_reservation)
        url = reverse(
            "admin:sistema_app_reservation_checkin_data",
            args=[active_reservation.checkin_token],
        )
        response = superuser_client.get(url)
        data = response.json()
        assert data["can_check_in"] is False
        assert data["status"] == Reservation.Status.USED

    def test_unauthenticated_redirects(self, client, active_reservation):
        """Cliente sin autenticar hace GET al endpoint con token válido; verifica que redirige."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_data",
            args=[active_reservation.checkin_token],
        )
        response = client.get(url)
        assert response.status_code in (302, 301)


@pytest.mark.django_db
@pytest.mark.integration
class TestAdminCheckinConfirmEndpoint:
    def test_confirm_transitions_active_to_used(self, superuser_client, active_reservation):
        """Superusuario hace POST al endpoint de confirmación; verifica HTTP 200, json['ok'] True, status USED en BD."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_confirm",
            args=[active_reservation.checkin_token],
        )
        response = superuser_client.post(url)
        assert response.status_code == 200
        data = response.json()
        assert data["ok"] is True
        assert data["status"] == Reservation.Status.USED
        active_reservation.refresh_from_db()
        assert active_reservation.status == Reservation.Status.USED

    def test_confirm_twice_returns_400(self, superuser_client, active_reservation):
        """Se confirma el check-in dos veces con el mismo token; verifica que la segunda responde HTTP 400 con clave 'error'."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_confirm",
            args=[active_reservation.checkin_token],
        )
        superuser_client.post(url)
        response = superuser_client.post(url)
        assert response.status_code == 400
        assert "error" in response.json()

    def test_confirm_cancelled_returns_400(self, superuser_client, cancelled_reservation):
        """Superusuario hace POST con el token de una reservación cancelada; verifica que responde HTTP 400."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_confirm",
            args=[cancelled_reservation.checkin_token],
        )
        response = superuser_client.post(url)
        assert response.status_code == 400

    def test_get_not_allowed(self, superuser_client, active_reservation):
        """Superusuario hace GET en lugar de POST al endpoint de confirmación; verifica que responde HTTP 405."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_confirm",
            args=[active_reservation.checkin_token],
        )
        response = superuser_client.get(url)
        assert response.status_code == 405

    def test_unknown_token_returns_404(self, superuser_client):
        """Superusuario hace POST con un UUID que no existe; verifica que responde HTTP 404."""
        url = reverse(
            "admin:sistema_app_reservation_checkin_confirm",
            args=[uuid.uuid4()],
        )
        response = superuser_client.post(url)
        assert response.status_code == 404
